### ISSUE TITLE
Task lists

### ISSUE THREAD

**Issue by bertolo1988** [dimpu/angular2-markdown#34]
[suggestion description](https://github.com/blog/1825-task-lists-in-all-markdown-documents)

I think this could be quite useful.

**Comment by dimpu** [comment]
We already have one https://github.com/dimpu/angular2-markdown#todo

**Comment by bertolo1988** [comment]
I tried to paste this:
```

## Todo

- [x] Variable binding
- [x] Code refactor
- [x] Write more unit tests
- [ ] Module configuration for markdown settings
- [ ] Module configuration for prismjs settings
```

in the [plunkr](https://plnkr.co/edit/haatIMLjfA0VbGeN4lGm?p=preview) and it did not work.

**Comment by dimpu** [comment]
Done! just update version to 1.5.0

see the demo at https://dimpu.github.io/angular2-markdown/todo
